#!/bin/bash

# Make sure this script is run alongside the hugo content 
# even if run as an executable.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

if [ -z "$(git status --porcelain -b)" ]; then
  # Working directory clean
  echo -e "\033[0;32mBuilding project...\033[0m"

  # Build the project.
  hugo -s ./

  echo -e "\033[0;32mCommitting changes...\033[0m"

  # Push build repos.
  git push git@github.com:pascalpdx/pascalpdx.github.io.git `git subtree split --prefix public master`:master --force

  echo -e "\033[0;32mChanges successfully published!\033[0m"
else 
  # Uncommitted changes
  echo -e "\033[0;32mYou must commit your changes before publishing\033[0m"
fi
