#!/bin/bash

# Make sure this script is run alongside the hugo content 
# even if run as an executable.

echo $GIT_SSH_COMMAND

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

if [ -n "$(git status --porcelain)" ]; then
  echo -e "\033[0;31mYou must commit and push your changes before publishing\033[0m"
  exit 1
elif [ -n "$(git status --porcelain -b|grep ahead)" ]; then
  echo -e "\033[0;31mYou must push your changes before publishing\033[0m"
  exit 1
else
  # Working directory clean
  echo -e "\033[0;32mBuilding project...\033[0m"

  # Build the project.
  HUGO_ENV=production hugo -v -s ./

  echo -e "\033[0;32mCommitting changes...\033[0m"

  # Push build repos.
  git push git@github.com:pascalpdx/pascalpdx.github.io.git `git subtree split --prefix public master`:master --force
  if [ $? != 0 ]; then
    echo -e "\033[0;31mChanges could not be published!\033[0m"
    exit 1
  fi
  echo -e "\033[0;32mChanges successfully published!\033[0m"
fi
